source 'https://rubygems.org'

gem 'virtus'
gem 'faraday'
gem 'faraday_middleware'
gem 'sinatra', require: false
gem 'erubis'
gem 'activesupport', require: 'active_support/all'

group :development do
  gem 'pry'
  gem 'awesome_print'
end
